# Generated by Django 3.2.5 on 2021-07-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=50)),
                ('contents', models.CharField(default='contents', max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
